import mongoose from 'mongoose';

const customerSchema = new mongoose.Schema({
  user_id: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: false },
  title: { type: String, default: '' },
  first_name: { type: String, required: true },
  middle_name: { type: String, default: '' },
  last_name: { type: String, required: true },
  suffix: { type: String, default: '' },
  legal_company_name: { type: String, default: '' },
  display_name: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  phone: { type: String, default: '' },
  cc_email: { type: String, default: '' },
  bcc_email: { type: String, default: '' },
  mobile: { type: String, default: '' },
  fax: { type: String, default: '' },
  other_contact: { type: String, default: '' },
  website: { type: String, default: '' },
  print_on_check_name: { type: String, default: '' },
  is_sub_customer: { type: Boolean, default: false },
  email_marketing_consent: { type: Boolean, default: false },
  billing_street_1: { type: String, default: '' },
  billing_street_2: { type: String, default: '' },
  billing_city: { type: String, default: '' },
  billing_state: { type: String, default: '' },
  billing_zip: { type: String, default: '' },
  billing_country: { type: String, default: 'USA' },
  shipping_same_as_billing: { type: Boolean, default: true },
  shipping_street_1: { type: String, default: '' },
  shipping_street_2: { type: String, default: '' },
  shipping_city: { type: String, default: '' },
  shipping_state: { type: String, default: '' },
  shipping_zip: { type: String, default: '' },
  shipping_country: { type: String, default: 'USA' },
  primary_payment_method: { type: String, default: '' },
  payment_terms: { type: String, default: '' },
  delivery_method: { type: String, default: '' },
  invoice_language: { type: String, default: 'English' },
  credit_limit: { type: Number, default: 0 },
  customer_type: { type: String, default: '' },
  tax_exempt: { type: Boolean, default: false },
  tax_rate_id: { type: String, default: '' },
  opening_balance: { type: Number, default: 0 },
  opening_balance_date: { type: String, default: '' },
  customer_role: { type: String, default: '' },
  primary_product_type: { type: String, default: '' },
  requires_certificate: { type: Boolean, default: false },
  requires_affidavit: { type: Boolean, default: false },
  requires_photo_video_proof: { type: Boolean, default: false },
  witness_required: { type: Boolean, default: false },
  scrap_resale_allowed: { type: Boolean, default: false },
  special_handling_notes: { type: String, default: '' },
  internal_notes: { type: String, default: '' },
  customer_status: { 
    type: String, 
    enum: ['active', 'on_hold', 'archived'], 
    default: 'active' 
  }
}, {
  timestamps: true
});

export default mongoose.models.Customer || mongoose.model('Customer', customerSchema);